# Generated by Django 3.2.6 on 2022-08-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220824_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', '-created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
